### PR TITLE
feat: mdTypes from core export

### PR DESCRIPTION
**Pull request by mshanemc**
### What does this PR do?
given that the file has been copied from the core test branch to SDR, add them to the registry

### What issues does this PR fix or reference?
@W-16495885@

### CODE REVIEW

**Review by shetzel — APPROVED** [review]

**Review by WillieRuemmele — APPROVED** [review]

**Comment by WillieRuemmele** [comment]
### QA Notes
---
❌  : 
```bash
sf alias set registryBuilder=<my org>

# changed metadata registry entries, expecting next command to revert changes
 ➜  yarn update-registry-org CustomField ListView customnotificationtype
yarn run v1.22.22
$ npx ts-node scripts/update-registry/updateRegistryFromOrg.ts CustomField ListView customnotificationtype
Will get describe for these types:
 - CustomField
 - ListView
 - customnotificationtype
[]
✨  Done in 2.85s.


# no changes to file
```

❌ : from the `contributing/metadata.md` => `Running the script with no params will try to do ALL missing metadata types.` => 
```bash
 ➜  yarn update-registry-org                                            
yarn run v1.22.22
$ npx ts-node scripts/update-registry/updateRegistryFromOrg.ts
/Users/william.ruemmele/projects/oss/source-deploy-retrieve/scripts/update-registry/updateRegistryFromOrg.ts:38
})();
  ^
Error: Please provide the types to update the registry with.  Ex: `yarn update-registry-org CustomObject CustomField`
    at /Users/william.ruemmele/projects/oss/source-deploy-retrieve/scripts/update-registry/updateRegistryFromOrg.ts:29:11
```

**Comment by mshanemc** [comment]
> ```shell
> yarn update-registry-org CustomField ListView customnotificationtype
> ```

fyi, customnotificationtype will work with the next change.  CustomField and ListView aren't in the describe because they're not top-level types but are children of CustomObject.

**Comment by mshanemc** [comment]
> Running the script with no params will try to do ALL missing metadata types

Ooh, good docs catch.  I meant to disable that option for the `org` version because there's such a low chance of success

**Comment by WillieRuemmele** [comment]
> > ```shell
> > yarn update-registry-org CustomField ListView customnotificationtype
> > ```
> 
> fyi, customnotificationtype will work with the next change. CustomField and ListView aren't in the describe because they're not top-level types but are children of CustomObject.

figured out the CF/LV wouldn't work, and then happened to choose another type that wouldn't work... unlucky on my part. I'll try again

**Comment by WillieRuemmele** [comment]
### QA Notes
---
🟡  : changed `ApexClass` entry, ran `yarn update-registry-org ApexClass` and it was updated, but it was missing `supportsWildCardAndName` field
✅ : same, `yarn update-registry-org apexclass`
✅ : will add missing type
✅ : must pass types to script
✅ : warning message for child types


🟡  : `yarn update-registry-core` will update types - `supportsWildCardAndName` missing as well, could require manual intervention - if it's possible to detect this, we should warn the user
✅ : `yarn update-registry-core` will add missing types
✅ : `yarn update-registry-core ApexClass`
✅ : `yarn update-registry-core apexclass`
✅ : warning message for child types

**Review by WillieRuemmele — APPROVED** [review]

**Pull request merged**
