### PR TITLE
Sm/remove-xml-dom

### PR DESCRIPTION
**Pull request by mshanemc**
### What does this PR do?
user normal maintained xmldom

### What issues does this PR fix or reference?
@W-11536555@

### CODE REVIEW

**Review by WillieRuemmele — APPROVED** [review]

**Review by gbockus-sf — APPROVED** [review]
This looks fine.  I dunno why we had the SF specific fork initially.  (Does anyone know?). I'll make a ticket to verify this change after we get our corev3 change merged.

**Comment by mshanemc** [comment]
> This looks fine. I dunno why we had the SF specific fork initially. (Does anyone know?). I'll make a ticket to verify this change after we get our corev3 change merged.

I don't know.  I don't know where the fork lives to check its changes, but the uses here are so lightweight that I'm guessin the regular version could handle it based on docs

**Review by gbockus-sf — APPROVED** [review]
So i dug deep into the VSCode side of how we are using SDR and I don't think we ever hit any of the Strategies code paths. We largely use the componentSet and related metadata deploy path so I was unable to actually exercise the code updated here. 

So take the QE for what it's worth but
✅ Does not impact VSCode functionality. Verified by tracing the usage of SDR in that tool and setting breakpoints and executing the various deploy/retrieve paths to ensure I wasn't just over looking the usage. 
✅ I compared the the [old repo](https://github.com/jindw/xmldom) with the [new repo](https://github.com/xmldom/xmldom) and I'm guessing the fork was only being used b/c they had some bugs that were fixed that must have been blocked behind a release they didn't want to wait on.  The new repo moved and doesn't have the history going back to 2013 but things look largely the same. 

 I think we're safe to merge this change.

**Comment by gbockus-sf** [comment]
I also pinged @AnanyaJha  in slack about why the strategies stuff exists.  She committed to it in the past.  We'll test her memory :)

**Pull request merged**
