### PR TITLE
fix: remove XML_NS_KEY from children when written in metadata format

### PR DESCRIPTION
**Pull request by WillieRuemmele**
### What does this PR do?
previously, child types would be written with `xmlns="http://soap.sforce.com/2006/04/metadata"` attribute in metadata format, this was unnecessary and made the xml harder to read

### What issues does this PR fix or reference?
mdapi-convereted files won't write child types with that attribute

https://github.com/forcedotcom/cli/issues/1142, @W-9803903@

### Functionality Before

<insert gif and/or summary>
```
    <compactLayouts xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Broker_Compact</fullName>
        <fields>Name</fields>
        <fields>Title__c</fields>
        <fields>Phone__c</fields>
        <fields>Mobile_Phone__c</fields>
        <fields>Email__c</fields>
        <label>Broker Compact</label>
    </compactLayouts>
```
### Functionality After
in dreamhouse-lwc, `sfdx force:source:convert -d output -m CustomObject` 
check `output/objects/Broker__c.object`
```
    <compactLayouts>
        <fullName>Broker_Compact</fullName>
        <fields>Name</fields>
        <fields>Title__c</fields>
        <fields>Phone__c</fields>
        <fields>Mobile_Phone__c</fields>
        <fields>Email__c</fields>
        <label>Broker Compact</label>
    </compactLayouts>

### CODE REVIEW

**Review by mshanemc — APPROVED** [review]

**Review by mshanemc — CHANGES_REQUESTED** [review]
Can you look into the NUTs on circle?  There's an odd error deploying the dreamhouse-lwc flow.   It happened several times

```
"componentFailures": {
        "changed": "false",
        "componentType": "Flow",
        "created": "false",
        "createdDate": "2021-09-15T22:55:03.000Z",
        "deleted": "false",
        "fileName": "flows/Create_property.flow",
        "fullName": "Create_property",
        "problem": "field integrity exception: unknown (The type for the input parameter \"Related Record ID\" doesn't match the type for the assigned value.)",
        "problemType": "Error",
        "success": "false"
      },
```

**Comment by WillieRuemmele** [comment]
@mshanemc it seems to be some flakiness in the NUTs, potentially from the signup slowness/setup commands. It seems like the setup commands didn't finish running before executing the test commands. I reran the NUTs and they 'passed' but failed with the `uncaught error outside of test suite` error we've been seeing on windows :(

**Review by shetzel — APPROVED** [review]

**Review by mshanemc — APPROVED** [review]

**Comment by kravuri1987** [comment]
@WillieRuemmele -How can we get this fix into our local sfdx cli?

**Comment by WillieRuemmele** [comment]
Hi @kravuri1987 this will be a part of the next `latest-rc` build of the cli (`7.120.0`) which will be released after Dreamforce

**Pull request merged**
